name: teknoloji_kimya_servis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eralpsoftware: ^1.0.0
  flutter_localizations:
    sdk: flutter
  http:
  barcode: ^2.1.0
  flutter_bloc: ^6.0.6
  get_it: ^5.0.1
  equatable: ^1.2.5
  provider: ^4.3.2+2
  flutter_slidable: ^0.5.7
  shared_preferences: ^2.0.9
  cloud_firestore: ^3.1.0
  firebase_core: ^1.10.0
  intl:
  flutter_speed_dial: ^3.0.5
  pdf: ^3.6.3
  path_provider: ^2.0.7
  open_file: ^3.0.3
  lazy_load_scrollview: ^1.1.0
  flushbar: ^1.10.4
  flutter_snake_navigationbar: ^0.4.2
  barcode_image: ^2.0.0
  qr_flutter: ^4.0.0
  printing: ^5.6.3
  url_launcher: ^6.0.2
  # pdf_flutter:
  #   git: https://github.com/erluxman/pdf_flutter
  flutter_barcode_scanner: ^2.0.0
  image_picker:
  photo_view: ^0.10.3
  webview_flutter: ^1.0.7
  table_calendar: ^2.3.3
  collection: ^1.14.13
  # google_fonts: ^1.1.2
  dio: ^4.0.4
  convex_bottom_bar: ^2.6.0
  flutter_emoji: ^2.2.1+1
  flutter_local_notifications: ^9.1.4
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  geolocator: ^7.7.1
  chewie: ^0.12.2
  cupertino_icons: ^1.0.0
  video_player: ^1.0.1
  cached_network_image: ^3.1.0+1
  animate_do: any
  firebase_messaging: any
  # get: ^3.26.0
  background_locator: ^1.5.0+1
  geocoder:
    git:
      url: https://github.com/nguyenxdat/flutter_geocoder.git
      ref: master
  google_maps_flutter: any
  permission_handler: any
  painter: ^0.4.0
  gallery_saver: ^2.0.3
  file_picker: any
  # esys_flutter_share: ^1.0.2
  firebase_storage: ^10.1.0
  share: ^2.0.4
  esys_flutter_share:
    git:
      url: https://github.com/cihadturhan/esys-flutter-share.git
      ref: nullsafety+embedding-2
  syncfusion_flutter_pdfviewer: ^19.3.55-beta

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/open.ttf
    - assets/mont.ttf
    - assets/montextrabold.ttf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\fonts\Montserrat-Black.ttf
        - asset: assets\fonts\Montserrat-BlackItalic.ttf
        - asset: assets\fonts\Montserrat-Bold.ttf
        - asset: assets\fonts\Montserrat-BoldItalic.ttf
        - asset: assets\fonts\Montserrat-ExtraBold.ttf
        - asset: assets\fonts\Montserrat-ExtraBoldItalic.ttf
        - asset: assets\fonts\Montserrat-ExtraLight.ttf
        - asset: assets\fonts\Montserrat-ExtraLightItalic.ttf
        - asset: assets\fonts\Montserrat-Italic.ttf
        - asset: assets\fonts\Montserrat-Light.ttf
        - asset: assets\fonts\Montserrat-LightItalic.ttf
        - asset: assets\fonts\Montserrat-Medium.ttf
        - asset: assets\fonts\Montserrat-MediumItalic.ttf
        - asset: assets\fonts\Montserrat-Regular.ttf
        - asset: assets\fonts\Montserrat-SemiBold.ttf
        - asset: assets\fonts\Montserrat-SemiBoldItalic.ttf
        - asset: assets\fonts\Montserrat-Thin.ttf
        - asset: assets\fonts\Montserrat-ThinItalic.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
